WITH CTE AS(
    SELECT EMPLOYEE_ID FROM EMPLOYEE
    GROUP BY EMPLOYEE_ID HAVING COUNT(*)=1
)
SELECT EMPLOYEE_ID, DEPARTMENT_ID
FROM EMPLOYEE
WHERE PRIMARY_FLAG='Y' OR EMPLOYEE_ID IN (SELECT * FROM CTE);